export interface Ref {
    leadDetails?: Record<string, any>;
    quarterlyRevenueYearMap: Record<string, any>;
    revenueProductIdMap?: Record<string, any>;
    revenueServiceTypeMap: Record<string, any>;
    dealDataProcIdMap: Record<string, any>;
    wonDealsDataProcIdMap: Record<string, any>;
    lostDealsDataProcIdMap: Record<string, any>;
    dealInstanceDataAccountIdMap: Record<string, any>;
    activeDealsDataProcIdMap: Record<string, any>;
    actualRevenueDealIdMap: Record<string, any>;
    expectedRevenueDealIdMap: Record<string, any>;
    quarterWiseRevenueColumnchartData: any[];
    allLeads: any[];
    chartRootQuarter: string;
    chartRootExpected: string;
    chartRootSuspended: string;
    chartRootDealOutcome: string;
    allDeals: any[];
    allLeadsData: any[];
    allDealData: any[];
    allAccountDetails: any[];
    expectedVsActualChartData: any[];
    monthlyRevenueYearMap: Record<string, any>;
    totalRevenue: number;
    totalExpectedRevenue: number;
    totalEarnedRevenue: number;
    totalProductWiseRevenue: number;
    currExpectedVsActualRevenueCount: number;
    widgetObj: any[];
    currentDate: any;
    defaultDatetimeFormat: string;
    begin?: string;
    end?: string;
    totalActualRevenue ?: number;
    totalExpectedNewRevenue ?: number;
    year ?: number;
    revExp ?: string;
    revBook ?: string;
    revEarn ?: string;
    leadIdentifier ?: any;
    allDetailsOfTable ?: any;
    sectorWiseData ?: any;
    fxRateIdMap ?: any;
    HeatMapData ?: any;
    PieChartData ?: any;
    DataOfSuccessTable ?: any;
    columnSchemaOfSuccessTable ?: any;
    columnSchemaOfSalesPerformanceTable ?: any;
    wonDeals : any[];
    lostDeals : any[];
    revenueDetailsDealIdMap ?: any;
    lineChartForDealsWon ?: any;
    allDealInstances ?: any[];
    dealCountDateMap ?: any;
    productProcessInstances : any[];
    overallDiscountDealIdMap ?: any;
    productDiscountProductIdMap ?: any;
    productsArrayProductTypeMap ?: any;
    dealDataProductTypeMap ?: any;
    productsWithNoQuotationData : any;
    productTypeProductTypeMap ?: any;
    productDataProcIdMap ?: any;
    dealDetailsTop: any[];
    productByProductNameData ?: any;
    quarterWiseRevenueColumnchartData2 ?: any;
    sectorRevenueChartData ?: any;
    WidgetDatas: Record<string,string|number>[];
}